[package]
name = "webhook-cli"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
source-keycloak-lib = { path="../source-keycloak-lib" }
clap = { version = "4.5.31", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12.15", features = ["default-tls", "native-tls"] }
url = "2.5.4"

[dev-dependencies]
