image: dr.rechenknecht.net/bauhelfer/container/main/rust:ubuntu-resolute

stages:
  - build
  - test
  - pack
  - test-e2e

variables:
  # This will instruct Docker not to start over TLS.
  DOCKER_TLS_CERTDIR: ""
  CARGO_HOME: $CI_PROJECT_DIR/.cargo

cache:
  # Cache per branch
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - target
    - ${CI_PROJECT_DIR}/.cargo

.binaries: &binaries
  - keycloak-memory
  - keycloak-synapse
  - keycloak-james
  - webhook-cli

.build_matrix: &build_matrix
  parallel:
    matrix:
      - BINARY: *binaries

############
# Building
############

build:
  stage: build
  <<: *build_matrix
  script:
    - RUSTFLAGS="-Dunused-crate-dependencies" cargo build --release --bin $BINARY
    # We store the version number here as the binary does not run with other Linux variants
    # (like this is built with GNU libc and the container with musl libc)
    - target/release/$BINARY -V > target/release/${BINARY}-version
  artifacts:
    paths:
      - target/release/$BINARY
      - target/release/${BINARY}-version
    expire_in: 1 week
    when: always
  needs: []

############
# Testing
############

lint:
  stage: test
  script:
    - rustup component add clippy
    - cargo clippy --all-targets -- -Dwarnings

fmt-check:
  stage: test
  script:
    - rustup component add rustfmt
    - cargo fmt --all -- --check

test-debug:
  stage: test
  script:
    - cargo llvm-cov --html --all-features
    - cargo llvm-cov report --cobertura --output-path target/llvm-cov/cobertura.xml
    - "xmllint --xpath \"concat('Coverage: ', 100 * string(//coverage/@line-rate), '%')\" target/llvm-cov/cobertura.xml"
  coverage: '/Coverage: \d+(?:\.\d+)?/'
  artifacts:
    paths:
      - target/llvm-cov/
    reports:
      coverage_report:
        coverage_format: cobertura
        path: target/llvm-cov/cobertura.xml

lint-cargo-toml:
  stage: test
  needs: []
  before_script:
    - cargo install cargo-sort
  script:
    - cargo sort --check --workspace && echo "Cargo.toml formatted correctly ✅"

############
# Build Container
############

docker-image:
  stage: pack
  <<: *build_matrix
  needs:
    - job: build
      artifacts: true
      parallel:
        matrix:
          - BINARY: *binaries
  image: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/library/docker:latest
  tags:
    # Use a privileged runner for building Docker container
    - privileged
  services:
    - name: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/library/docker:dind
      alias: docker
  variables:
    # This will instruct Docker not to start over TLS.
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - export IMAGE_NAME=$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG/$BINARY
    - export BINARY_VERSION=`cat target/release/${BINARY}-version | cut -d ' ' -f2`
    - export BINARY_VERSION_MAJOR=`echo $BINARY_VERSION | cut -d '.' -f1`
    - export BINARY_VERSION_MINOR=`echo $BINARY_VERSION | cut -d '.' -f2`
    - export BINARY_VERSION_PATCH=`echo $BINARY_VERSION | cut -d '.' -f3`
    - docker build
        --build-arg "BINARY=$BINARY"
        -t "$IMAGE_NAME:latest"
        -t "$IMAGE_NAME:pipeline-$CI_PIPELINE_IID"
        -t "$IMAGE_NAME:v-$BINARY_VERSION_MAJOR"
        -t "$IMAGE_NAME:v-$BINARY_VERSION_MAJOR.$BINARY_VERSION_MINOR"
        -t "$IMAGE_NAME:v-$BINARY_VERSION_MAJOR.$BINARY_VERSION_MINOR.$BINARY_VERSION_PATCH"
        --push
        .

############
# E2E Testing
############

test-synapse-e2e:
  stage: test-e2e
  image: quay.io/podman/stable:latest
  needs:
    - job: docker-image
      artifacts: true
      parallel:
        matrix:
          - BINARY: keycloak-synapse
  tags:
    # Use a privileged runner for running (Docker) containers.
    - privileged
  script:
    - echo "Install dependencies"
    - dnf install unzip envsubst openssl jq --assumeyes --refresh
    - python -m ensurepip --upgrade
    - python -m pip install pyyaml
    - python -m pip install synadm
    - echo "$CI_REGISTRY_PASSWORD" | podman login --username $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - echo "127.0.0.1 host.docker.internal" >> /etc/hosts
    - pushd e2e-test
    - source .env
    - echo "Download Keycloak Webhook SPI"
    - pushd keycloak
    - >
      curl --output artifacts.zip --header "PRIVATE-TOKEN: $KEYCLOAK_WEBHOOK_SPI_DOWNLOAD"
      "https://rechenknecht.net/api/v4/projects/192/jobs/artifacts/main/download?job=build-jar"
    - unzip artifacts.zip
    - rm artifacts.zip
    - mv build/libs/* .
    - rmdir -p build/libs
    - popd
    - echo "Start Synapse & Keycloak"
    - ./setup_synapse_e2e.sh
    - echo "Start KIDS"
    - KIDS_PODMAN_ID=$(podman run -d -v $(realpath config/synapse_e2e_config.toml):/config.toml --net host $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG/keycloak-synapse:latest --config /config.toml)
    - echo "Waiting for KIDS to sync..."
    - sleep 10
    - podman logs $KIDS_PODMAN_ID
    - PODMAN_SERVICE_HOSTNAME=$PODMAN_SERVICE_HOSTNAME SYNAPSE_TLS_PORT=$SYNAPSE_TLS_PORT ./verify_synapse_e2e.sh
    - podman stop $KIDS_PODMAN_ID && podman rm $KIDS_PODMAN_ID
    - ./teardown_synapse_e2e.sh
