image: dr.rechenknecht.net/bauhelfer/container/main/rust:ubuntu-jammy

stages:
  - build
  - test
  - pack

variables:
  # This will instruct Docker not to start over TLS.
  DOCKER_TLS_CERTDIR: ""
  CARGO_HOME: $CI_PROJECT_DIR/.cargo

cache:
  # Cache per branch
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - target
    - ${CI_PROJECT_DIR}/.cargo

############
# Building
############

build-release:
  stage: build
  script:
    - cargo build --release --verbose
  artifacts:
    paths:
      - target/release/
    expire_in: 1 week
    when: always

build-debug:
  stage: build
  script:
    - cargo build --verbose
  artifacts:
    paths:
      - target/debug/
    expire_in: 1 week
    when: always

############
# Testing
############

lint:
  stage: test
  script:
    - rustup component add clippy
    - cargo clippy --all-targets -- -Dwarnings
  needs:
    - build-debug

fmt-check:
  stage: test
  script:
    - rustup component add rustfmt
    - cargo fmt --all -- --check
  needs:
    - build-debug

test-debug:
  stage: test
  script:
    - cargo llvm-cov --html --all-features
    - cargo llvm-cov report --cobertura --output-path target/llvm-cov/cobertura.xml
    - "xmllint --xpath \"concat('Coverage: ', 100 * string(//coverage/@line-rate), '%')\" target/llvm-cov/cobertura.xml"
  coverage: '/Coverage: \d+(?:\.\d+)?/'
  artifacts:
    paths:
      - target/llvm-cov/
    reports:
      coverage_report:
        coverage_format: cobertura
        path: target/llvm-cov/cobertura.xml

  needs:
    - build-debug

############
# Pack
############

docker-image:
  stage: pack
  image: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/library/docker:latest
  needs:
    - job: build-release
      artifacts: true
  tags:
    # Use a privileged runner for building Docker container
    - privileged
  services:
    - name: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/library/docker:dind
      alias: docker
  variables:
    # This will instruct Docker not to start over TLS.
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - |+
      build() {
        TARGET_BINARY=$1
        IMAGE_NAME=$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG/$TARGET_BINARY
        docker build \
          --build-arg "BINARY=$TARGET_BINARY" \
          -t "$IMAGE_NAME:latest" \
          -t "$IMAGE_NAME:$CI_PIPELINE_IID" \
          --push .
      }
    - build keycloak-james
    - build keycloak-synapse
