[workspace]
resolver = "3"
members = [
    "keycloak-james",
    "keycloak-memory",
    "keycloak-synapse",
    "kids-lib",
    "source-keycloak-lib",
    "webhook-cli",
]

[workspace.lints.clippy]
needless_pass_by_ref_mut = "deny"

[profile.test.package."*"]
# To make recompiling tests a bit faster, see
# https://www.reddit.com/r/bevy/comments/1jtrcdy/unit_tests_recompile_all_dependencies_every_time/
# This problem only occurs since Rust 1.86.0
opt-level = 3
