# For documentation on the configuration parameters, refer to the default_configs directory.
# This file does intentionally not contain any parameter comments, as those could get out of sync quite easily.

[http]
bind_addr = "127.0.0.1:3000"

[sentry]
active = false
dsn = "https://2b259ab7638c4a71ab3fca497e2c5295@sentry.giz.berlin/22"
environment = "develop"

[source]
[source.keycloak_api]
keycloak_address = "https://$PODMAN_SERVICE_HOSTNAME:8443"
client_id = "keycloak_identity_syncer"
client_secret = "keycloak_identity_syncer_secret"
realm = "giz"
insecure_disable_tls_verification = true

[target]
source_room_name_attr = "matrixRoomName"
room_deletion_strategy = "KickAll"
[target.synapse_api]
matrix_homeserver_url = "https://$PODMAN_SERVICE_HOSTNAME:$SYNAPSE_TLS_PORT"
matrix_source_oidc_provider_id = "keycloak"
matrix_syncer_user_id = "@admin:$PODMAN_SERVICE_HOSTNAME:$SYNAPSE_TLS_PORT"
matrix_syncer_password = "password"
matrix_namespace = "$PODMAN_SERVICE_HOSTNAME:$SYNAPSE_TLS_PORT"
insecure_disable_tls_verification = true
