[package]
name = "keycloak-kentix"
description = "Keycloak to Kentix identity syncer — synchronizes users and roles from Keycloak to a Kentix server via webhook endpoints"
homepage = "https://rechenknecht.net/giz/keycloak/kids/-/tree/main/keycloak-kentix"
version = "0.1.1"
edition = "2024"
publish = false

[dependencies]
anyhow = "1"
async-trait = "0.1.88"
http = "1.2.0"
kids-lib = { path = "../kids-lib" }
reqwest = { version = "0.12.15", features = ["default-tls", "native-tls"] }
serde = { version = "1.0.218", features = ["serde_derive"] }
serde_json = "1.0.140"
source-keycloak-lib = { path = "../source-keycloak-lib" }
tracing = "0.1"
url = "2.5.4"

[dev-dependencies]
kids-test-lib = { path = "../kids-test-lib" }
mockall = "0.13.1"
rstest = "0.25.0"
tokio = { version = "1", features = ["full"] }
typed-builder = "0.23.2"
