### General & controller configuration
[controller]
# Address with port to bind the HTTP server to, e.g. 127.0.0.1:3000
bind_addr = ""
# Interval in seconds to perform the full sync from source to target.
# Defaults to 24h.
# full_sync_interval_seconds = 86400

# TLS configuration.
# Set mode = "insecure_disabled" to serve plain HTTP (do not use in production).
[controller.tls]
mode = "enabled"
cert_pem = """
-----BEGIN CERTIFICATE-----
...contents of server.crt...
-----END CERTIFICATE-----
"""
key_pem = """
-----BEGIN PRIVATE KEY-----
...contents of server.key...
-----END PRIVATE KEY-----
"""

# Client certificate authentication.
# Set mode = "insecure_disabled" to allow unauthenticated access (do not use in production).
[controller.tls.client_auth]
mode = "enabled"

[[controller.tls.client_auth.clients]]
name = "keycloak"
cert_pem = """
-----BEGIN CERTIFICATE-----
...contents of keycloak-client.crt...
-----END CERTIFICATE-----
"""
# Whether to grant access to the webhook routes such as /v1/users and /v1/groups
# allow_webhook_access = false

# This section can be omitted to disable Sentry.
[sentry]
# Sentry Data Source Name (DSN). Tells Sentry where to send events to so they're associated with the correct project.
# Must be specified if this section is present.
# See https://docs.sentry.io/platforms/rust/#configure
dsn = ""
# Tag specifying which context the service is running in (for example, alice-develop, production, ...)
# Must be present if this section is present.
# See https://docs.sentry.io/platforms/rust/configuration/environments/
environment = ""

### Source configuration
# [source]
# ... insert source config here, see *-source.config.example.toml files

### Target configuration
# [target]
# ... insert target config here, see *-target.config.example.toml files
