[source]

[source.keycloak_api]
# Address of the external Keycloak to fetch data from.
keycloak_address = "http://localhost:8080"
# Credentials of a Keycloak service account used to fetch the data.
# The service account needs to have access to the realm and have the "view-users" and "view-realm" roles assigned.
# Otherwise, the API will report an authentication error as it is not able to access the desired information,
# even when the credentials are valid.
client_id = "keycloak_identity_syncer"
client_secret = "keycloak_identity_syncer_secret"
# Keycloak realm to fetch the data from.
realm = "giz"
# Whether to validate the server certificate of the external API.
# Only disable for local development purposes!
insecure_disable_tls_verification = false
